version: "3.8"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: vision
      POSTGRES_PASSWORD: visionpass
      POSTGRES_DB: vision_sacco
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  backend:
    build: ./server
    command: npm run dev
    volumes:
      - ./server:/app
    env_file:
      - .env
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis

  frontend:
    build: ./ (if you want to dockerize frontend) 
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  pgdata:
